services:
  nginx:
    image: "vracine/multi-nginx:TAG_PLACEHOLDER"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
      - client

  api:
    image: "vracine/multi-server:TAG_PLACEHOLDER"
    restart: always
    environment:
      - REDIS_HOST=YOUR_ELASTICACHE_ENDPOINT
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=YOUR_RDS_ENDPOINT
      - PGDATABASE=fibvalues
      - PGPASSWORD=YOUR_RDS_PASSWORD
      - PGPORT=5432

  client:
    image: "vracine/multi-client:TAG_PLACEHOLDER"
    restart: always

  worker:
    image: "vracine/multi-worker:TAG_PLACEHOLDER"
    restart: always
    environment:
      - REDIS_HOST=YOUR_ELASTICACHE_ENDPOINT
      - REDIS_PORT=6379
