name: Deploy

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build production images
        run: |
          docker build -t vracine/multi-client:${{ github.ref_name }} -t vracine/multi-client:latest ./client
          docker build -t vracine/multi-nginx:${{ github.ref_name }} -t vracine/multi-nginx:latest ./nginx
          docker build -t vracine/multi-server:${{ github.ref_name }} -t vracine/multi-server:latest ./server
          docker build -t vracine/multi-worker:${{ github.ref_name }} -t vracine/multi-worker:latest ./worker

      - name: Push images to Docker Hub
        run: |
          docker push vracine/multi-client:${{ github.ref_name }}
          docker push vracine/multi-client:latest
          docker push vracine/multi-nginx:${{ github.ref_name }}
          docker push vracine/multi-nginx:latest
          docker push vracine/multi-server:${{ github.ref_name }}
          docker push vracine/multi-server:latest
          docker push vracine/multi-worker:${{ github.ref_name }}
          docker push vracine/multi-worker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Inject Secrets
        run: |
          sed -i "s|TAG_PLACEHOLDER|${{ github.ref_name }}|g" docker-compose.yml
          sed -i "s|YOUR_RDS_ENDPOINT|${{ secrets.RDS_ENDPOINT }}|g" docker-compose.yml
          sed -i "s|YOUR_RDS_PASSWORD|${{ secrets.RDS_PASSWORD }}|g" docker-compose.yml
          sed -i "s|YOUR_ELASTICACHE_ENDPOINT|${{ secrets.ELASTICACHE_ENDPOINT }}|g" docker-compose.yml

      - name: Generate deployment package
        run: zip -r deploy.zip docker-compose.yml

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          region: us-east-2
          version_label: ${{ github.ref_name }}
          deployment_package: deploy.zip
